services:
  - type: web
    name: pterodactyl-wings
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
